create table websites (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    url varchar(2048) not null,
    status varchar(255),
    tag varchar(50),
    check_interval_seconds integer not null default 60,
    enabled boolean not null default true,
    publicly_visible boolean not null default false,
    failure_threshold integer not null default 3,
    recovery_threshold integer not null default 2,
    consecutive_failures integer not null default 0,
    consecutive_successes integer not null default 0,
    last_successful_check_at timestamp,
    last_failed_check_at timestamp,
    last_failure_reason varchar(1000),
    last_http_status_code integer,
    last_response_time bigint,
    constraint uk_websites_url unique (url),
    constraint chk_websites_status check (status is null or status in ('UP', 'DOWN')),
    constraint chk_websites_interval check (check_interval_seconds between 10 and 3600),
    constraint chk_websites_failure_threshold check (failure_threshold between 1 and 10),
    constraint chk_websites_recovery_threshold check (recovery_threshold between 1 and 10),
    constraint chk_websites_failure_count check (consecutive_failures >= 0),
    constraint chk_websites_success_count check (consecutive_successes >= 0),
    constraint chk_websites_response_time check (last_response_time is null or last_response_time >= 0)
);

create table monitoring_results (
    id bigint generated by default as identity primary key,
    website_id bigint not null references websites(id) on delete cascade,
    status varchar(255) not null,
    response_time bigint not null,
    http_status_code integer,
    failure_reason varchar(1000),
    checked_at timestamp not null,
    constraint chk_monitoring_results_status check (status in ('UP', 'DOWN')),
    constraint chk_monitoring_results_response_time check (response_time >= 0),
    constraint chk_monitoring_results_http_status check (
        http_status_code is null or http_status_code between 100 and 599
    )
);

create table incidents (
    id bigint generated by default as identity primary key,
    website_id bigint not null references websites(id) on delete cascade,
    started_at timestamp not null,
    resolved_at timestamp,
    duration_seconds bigint,
    status varchar(255) not null,
    constraint chk_incidents_status check (status in ('OPEN', 'RESOLVED')),
    constraint chk_incidents_duration check (duration_seconds is null or duration_seconds >= 0)
);

create table alert_events (
    id bigint generated by default as identity primary key,
    website_id bigint not null references websites(id) on delete cascade,
    type varchar(255) not null,
    severity varchar(255) not null,
    channel varchar(255) not null,
    message varchar(1000) not null,
    created_at timestamp not null,
    constraint chk_alert_events_type check (type in ('DOWNTIME', 'RECOVERY')),
    constraint chk_alert_events_severity check (severity in ('CRITICAL', 'INFO')),
    constraint chk_alert_events_channel check (channel in ('EMAIL'))
);

create index idx_monitoring_results_checked_at
    on monitoring_results (checked_at);
create index idx_monitoring_results_website_checked_at
    on monitoring_results (website_id, checked_at);
create index idx_incidents_website_started_at
    on incidents (website_id, started_at);
create index idx_incidents_website_status_started_at
    on incidents (website_id, status, started_at);
create index idx_alert_events_website_created_at
    on alert_events (website_id, created_at);
